//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class allFan
    {
        public string username { get; set; }
        public string pswd { get; set; }
        public string fname { get; set; }
        public int nationalID { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<bool> unblocked { get; set; }
    }
}
