//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fan()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int nationalID { get; set; }
        public string fname { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> phoneNo { get; set; }
        public Nullable<bool> unblocked { get; set; }
        public string faddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
