//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stadium()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int id { get; set; }
        public Nullable<int> stadiumManagerID { get; set; }
        public string sname { get; set; }
        public Nullable<bool> available { get; set; }
        public Nullable<int> capacity { get; set; }
        public string slocation { get; set; }
        public string username { get; set; }
        public string pswd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        public virtual StadiumManager StadiumManager { get; set; }
    }
}
